test aws sct

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -33,7 +33,25 @@ phases:
     commands:
       - echo Build started on `date`
       - echo source db $SOURCE_RDS_ARN
-      - aws iam get-user
+      - |
+        handle_error() {
+          echo "An error occurred"
+          # Add any necessary cleanup or error handling logic here
+          exit 1
+        }
+        
+        # Try block
+        try {
+          echo "Performing some aws cli option..."
+          aws iam get-user
+        }
+        
+        # Catch block
+        catch {
+          handle_error
+        }
+        
+
       #source external database 
       # - aws sct convert-schema \
       #   --source-arn "jdbc:postgresql://$SOURCE_SERVER_NAME:5432/$SOURCE_DATABASE_NAME" \
